#!/bin/env ruby
# encoding: utf-8

# frozen_string_literal: true

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Page.new
Page.create(chapter: 0 ,section: 0 ,title: "Preface" )
Page.create(chapter: -1 ,section: 1 ,title: "Engineering Software as a Service: An Agile Approach Using Cloud Computing" )
Page.create(chapter: -1 ,section: 2 ,title: "Search the Book" )

Page.create(chapter: 1,section: 0 ,title: "Introduction to Software as a Service, Agile Development, and Cloud Computing" )
Page.create(chapter: 1 ,section: 1 ,title: "Introduction" )
Page.create(chapter: 1 ,section: 2 ,title: "Software Development Processes: Plan and Document" )
Page.create(chapter: 1 ,section: 3 ,title: "Software Development Processes: The Agile Manifesto" )
Page.create(chapter: 1 ,section: 4 ,title: "Software Quality Assurance: Testing" )
Page.create(chapter: 1 ,section: 5 ,title: "Productivity: Conciseness, Synthesis, Reuse, and Tools" )
Page.create(chapter: 1 ,section: 6 ,title: "SaaS and Service Oriented Architecture" )
Page.create(chapter: 1 ,section: 7 ,title: "Deploying SaaS: Cloud Computing" )
Page.create(chapter: 1 ,section: 8 ,title: "Deploying SaaS: Browsers and Mobile" )
Page.create(chapter: 1 ,section: 9 ,title: "Beautiful vs. Legacy Code" )
Page.create(chapter: 1 ,section: 10 ,title: "Guided Tour and How To Use This Book" )
Page.create(chapter: 1 ,section: 11 ,title: "Fallacies and Pitfalls" )
Page.create(chapter: 1 ,section: 12 ,title: "Concluding Remarks: Software Engineering Is More Than Programming" )
Page.create(chapter: 2 ,section: 0 ,title: "How to Learn a New Language" )
Page.create(chapter: 2 ,section: 1 ,title: "Prelude: Learning to Learn Languages and Frameworks" )
Page.create(chapter: 2 ,section: 2 ,title: "Pair Programming" )
Page.create(chapter: 2 ,section: 3 ,title: "Introducing Ruby,an Object-Oriented Language" )
Page.create(chapter: 2 ,section: 4 ,title: "Ruby Idioms: Poetry Mode, Blocks, Duck Typing" )
Page.create(chapter: 2 ,section: 5 ,title: "CHIPS: Ruby Intro" )
Page.create(chapter: 2 ,section: 6 ,title: "Gems and Bundler: Library Management in Ruby" )
Page.create(chapter: 2 ,section: 7 ,title: "Fallacies and Pitfalls" )
Page.create(chapter: 2 ,section: 8 ,title: "Concluding Remarks: How (Not) To Learn a Language By Googling" )
Page.create(chapter: 3 ,section: 0 ,title: "SaaS Application Architecture: Microservices, APIs, and REST" )
Page.create(chapter: 3 ,section: 1 ,title: "Introduction" )
Page.create(chapter: 3 ,section: 2 ,title: "SaaS Communication Uses HTTP Routes" )
Page.create(chapter: 3 ,section: 3 ,title: "CHIPS: HTTP and URIs" )
Page.create(chapter: 3 ,section: 4 ,title: "From Web Sites to Microservices: Service-Oriented Architecture" )
Page.create(chapter: 3 ,section: 5 ,title: "RESTful APIs: Everything is a Resource" )
Page.create(chapter: 3 ,section: 6 ,title: "RESTful URIs, API Calls, and JSON" )
Page.create(chapter: 3 ,section: 7 ,title: "CHIPS: Create and Deploy a Simple SaaS App" )
Page.create(chapter: 3 ,section: 8 ,title: "Fallacies and Pitfalls" )
Page.create(chapter: 3 ,section: 9 ,title: "Concluding Remarks: Continuity From CGI to SOA" )
Page.create(chapter: 4 ,section: 0 ,title: "SaaS Framework: Rails as a Model-View-Controller Framework" )
Page.create(chapter: 4 ,section: 1 ,title: "The Model-View-Controller (MVC) Architecture" )
Page.create(chapter: 4 ,section: 2 ,title: "Rails Models: Databases and Active Record" )
Page.create(chapter: 4 ,section: 3 ,title: "CHIPS: ActiveRecord Basics" )
Page.create(chapter: 4 ,section: 4 ,title: "Routes, Controllers, and Views" )
Page.create(chapter: 4 ,section: 5 ,title: "CHIPS: Rails Routes" )
Page.create(chapter: 4 ,section: 6 ,title: "Forms" )
Page.create(chapter: 4 ,section: 7 ,title: "CHIPS: Hangperson on Rails" )
Page.create(chapter: 4 ,section: 8 ,title: "Debugging: When Things Go Wrong" )
Page.create(chapter: 4 ,section: 9 ,title: "CHIPS: Hello Rails" )
Page.create(chapter: 4 ,section: 10 ,title: "Fallacies and Pitfalls" )
Page.create(chapter: 4 ,section: 11 ,title: "Concluding Remarks: Rails as a Service Framework" )
Page.create(chapter: 5 ,section: 0 ,title: "SaaS Framework: Advanced Programming Abstractions for SaaS" )
Page.create(chapter: 5 ,section: 1 ,title: "DRYing Out MVC: Partials, Validations and Filters" )
Page.create(chapter: 5 ,section: 2 ,title: "Single Sign-On and Third-Party Authentication" )
Page.create(chapter: 5 ,section: 3 ,title: "CHIPS: Rails Intro" )
Page.create(chapter: 5 ,section: 4 ,title: "Associations and Foreign Keys" )
Page.create(chapter: 5 ,section: 5 ,title: "Through-Associations" )
Page.create(chapter: 5 ,section: 6 ,title: "RESTful Routes for Associations" )
Page.create(chapter: 5 ,section: 7 ,title: "CHIPS: Associations" )
Page.create(chapter: 5 ,section: 8 ,title: "Other Types of Code" )
Page.create(chapter: 5 ,section: 9 ,title: "Fallacies and Pitfalls" )
Page.create(chapter: 5 ,section: 10 ,title: "Concluding Remarks: Languages, Productivity, and Beauty" )
Page.create(chapter: 6 ,section: 0 ,title: "Mobile and Desktop SaaS Clients: JavaScript Introduction" )
Page.create(chapter: 6 ,section: 1 ,title: "JavaScript: The Big Picture" )
Page.create(chapter: 6 ,section: 2 ,title: "Introducing ECMAScript" )
Page.create(chapter: 6 ,section: 3 ,title: "Classes, Functions and Constructors" )
Page.create(chapter: 6 ,section: 4 ,title: "The Document Object Model (DOM) and jQuery" )
Page.create(chapter: 6 ,section: 5 ,title: "The DOM and Accessibility" )
Page.create(chapter: 6 ,section: 6 ,title: "Events and Callbacks" )
Page.create(chapter: 6 ,section: 7 ,title: "AJAX: Asynchronous JavaScript And XML" )
Page.create(chapter: 6 ,section: 8 ,title: "Testing Java Script and AJAX" )
Page.create(chapter: 6 ,section: 9 ,title: "CHIPS: AJAX Enhancements to RottenPotatoes" )
Page.create(chapter: 6 ,section: 10 ,title: "Single-Page Apps and JSON APIs" )
Page.create(chapter: 6 ,section: 11 ,title: "Fallacies and Pitfalls" )
Page.create(chapter: 6 ,section: 12 ,title: "Concluding Remarks: JavaScript Past, Present and Future" )
Page.create(chapter: 7 ,section: 0 ,title: "Requirements: BDD and User Stories" )
Page.create(chapter: 7 ,section: 1 ,title: "Behavior-Driven Design and User Stories" )
Page.create(chapter: 7 ,section: 2 ,title: "SMART User Stories" )
Page.create(chapter: 7 ,section: 3 ,title: "Lo-Fi User Interface Sketches and Storyboards" )
Page.create(chapter: 7 ,section: 4 ,title: "Points and Velocity" )
Page.create(chapter: 7 ,section: 5 ,title: "Agile Cost Estimation" )
Page.create(chapter: 7 ,section: 6 ,title: "Cucumber: From User Stories to Acceptance Tests" )
Page.create(chapter: 7 ,section: 7 ,title: "CHIPS: Intro to BDD and Cucumber" )
Page.create(chapter: 7 ,section: 8 ,title: "Explicit vs. Implicit and Imperative vs. Declarative Scenarios" )
Page.create(chapter: 7 ,section: 9 ,title: "The Plan-And-Document Perspective on Documentation" )
Page.create(chapter: 7 ,section: 10 ,title: "Fallacies and Pitfalls" )
Page.create(chapter: 7 ,section: 11 ,title: "Concluding Remarks: Pros and Cons of BDD" )
Page.create(chapter: 8 ,section: 0 ,title: "Testing: Test-Driven Development" )
Page.create(chapter: 8 ,section: 1 ,title: "FIRST, TDD, and Red-Green-Refactor" )
Page.create(chapter: 8 ,section: 2 ,title: "Anatomy of a Test Case: Arrange, Act, Assert" )
Page.create(chapter: 8 ,section: 3 ,title: "Isolating Code: Doubles and Seams" )
Page.create(chapter: 8 ,section: 4 ,title: "Stubbing the Internet" )
Page.create(chapter: 8 ,section: 5 ,title: "CHIPS: Intro to RSpec on Rails" )
Page.create(chapter: 8 ,section: 6 ,title: "Fixtures and Factories" )
Page.create(chapter: 8 ,section: 7 ,title: "Coverage Concepts and Types of Tests" )
Page.create(chapter: 8 ,section: 8 ,title: "Other Testing Approaches and Terminology" )
Page.create(chapter: 8 ,section: 9 ,title: "CHIPS:The Acceptance Test/Unit Test Cycle" )
Page.create(chapter: 8 ,section: 10 ,title: "The Plan-And-Document Perspective on Testing" )
Page.create(chapter: 8 ,section: 11 ,title: "Fallacies and Pitfalls" )
Page.create(chapter: 8 ,section: 12 ,title: "Concluding Remarks: TDD vs. Conventional Debugging" )
Page.create(chapter: 9 ,section: 0 ,title: "Software Maintenance: Enhancing Legacy Software Using Refactoring and Agile Methods" )
Page.create(chapter: 9 ,section: 1 ,title: "What Makes Code \" Legacy \" and How Can Agile Help?" )
Page.create(chapter: 9 ,section: 2 ,title: "Exploring a Legacy Codebase" )
Page.create(chapter: 9 ,section: 3 ,title: "Establishing Ground Truth With Characterization Tests" )
Page.create(chapter: 9 ,section: 4 ,title: "Comments and Commits: Documenting Code" )
Page.create(chapter: 9 ,section: 5 ,title: "Metrics, CodeSmells, and SOFA" )
Page.create(chapter: 9 ,section: 6 ,title: "Method-Level Refactoring: Replacing Dependencies With Seams" )
Page.create(chapter: 9 ,section: 7 ,title: "The Plan-And-Document Perspective on Working With Legacy Code" )
Page.create(chapter: 9 ,section: 8 ,title: "Fallacies and Pitfalls" )
Page.create(chapter: 9 ,section: 9 ,title: "Concluding Remarks: Continuous Refactoring" )
Page.create(chapter: 10 ,section: 0 ,title: "Agile Teams" )
Page.create(chapter: 10 ,section: 1 ,title: "It Takes a Team: Two-Pizza and Scrum" )
Page.create(chapter: 10 ,section: 2 ,title: "Using Branches Effectively" )
Page.create(chapter: 10 ,section: 3 ,title: "Pull Requests and Code Reviews" )
Page.create(chapter: 10 ,section: 4 ,title: "Delivering the Backlog Using Continuous Integration" )
Page.create(chapter: 10 ,section: 5 ,title: "CHIPS: Agile Iterations" )
Page.create(chapter: 10 ,section: 6 ,title: "Reporting and Fixing Bugs: The Five R's" )
Page.create(chapter: 10 ,section: 7 ,title: "The Plan-And-Document Perspective on Managing Teams" )
Page.create(chapter: 10 ,section: 8 ,title: "Fallacies and Pitfalls" )
Page.create(chapter: 10 ,section: 9 ,title: "Concluding Remarks: From Solo Developer to Teams of Teams" )
Page.create(chapter: 11 ,section: 0 ,title: "Design Patterns for SaaS Apps" )
Page.create(chapter: 11 ,section: 1 ,title: "Patterns, Antipatterns, and SOLID Class Architecture" )
Page.create(chapter: 11 ,section: 2 ,title: "Just Enough UML" )
Page.create(chapter: 11 ,section: 3 ,title: "Single Responsibility Principle" )
Page.create(chapter: 11 ,section: 4 ,title: "Open/Closed Principle" )
Page.create(chapter: 11 ,section: 5 ,title: "Liskov Substitution Principle" )
Page.create(chapter: 11 ,section: 6 ,title: "Dependency Injection Principle" )
Page.create(chapter: 11 ,section: 7 ,title: "Demeter Principle" )
Page.create(chapter: 11 ,section: 8 ,title: "The Plan-And-Document Perspective on Design Patterns" )
Page.create(chapter: 11 ,section: 9 ,title: "Fallacies and Pitfalls" )
Page.create(chapter: 11 ,section: 10 ,title: "Concluding Remarks: Frameworks Capture Design Patterns" )
Page.create(chapter: 12 ,section: 0 ,title: "Dev/Ops" )
Page.create(chapter: 12 ,section: 1 ,title: "From Development to Deployment" )
Page.create(chapter: 12 ,section: 2 ,title: "Three-Tier Architecture" )
Page.create(chapter: 12 ,section: 3 ,title: "Responsiveness, Service Level Objectives, and Apdex" )
Page.create(chapter: 12 ,section: 4 ,title: "Releases and Feature Flags" )
Page.create(chapter: 12 ,section: 5 ,title: "Monitoring and Finding Bottlenecks" )
Page.create(chapter: 12 ,section: 6 ,title: "Improving Rendering and Database Performance With Caching" )
Page.create(chapter: 12 ,section: 7 ,title: "Avoiding Abusive Database Queries" )
Page.create(chapter: 12 ,section: 8 ,title: "CHIPS: Exploiting Caching and Indices" )
Page.create(chapter: 12 ,section: 9 ,title: "Security: Defending Customer Data in Your App" )
Page.create(chapter: 12 ,section: 10 ,title: "The Plan-And-Document Perspective on Operations" )
Page.create(chapter: 12 ,section: 11 ,title: "Fallacies and Pitfalls" )
Page.create(chapter: 12 ,section: 12 ,title: "Concluding Remarks: Beyond PaaS Basics" )
Page.create(chapter: 13 ,section: 0 ,title: "Afterword" )
Page.create(chapter: 13 ,section: 1 ,title: "Looking Backwards" )
Page.create(chapter: 13 ,section: 2 ,title: "Looking Forwards" )
Page.create(chapter: 13 ,section: 3 ,title: "Essential Readings" )
Page.create(chapter: 13 ,section: 4 ,title: "Last Words" )



